version: '3'

services:
  transactions:
    build:
      context: .
      dockerfile: Dockerfile
    image: ms-transactions:latest
    ports:
      - "3001:3001"
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
    volumes:
      - .:/usr/src/app

  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - transactions_data:/var/lib/postgresql/data

volumes:
  transactions_data:
    driver: local